# Generated by Django 5.2.13 on 2026-04-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('flag', models.CharField(blank=True, max_length=4)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
