# Generated by Django 5.2.13 on 2026-04-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_language',
            field=models.CharField(blank=True, choices=[('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('zh', 'Mandarin Chinese'), ('ko', 'Korean'), ('ar', 'Arabic'), ('ru', 'Russian')], max_length=10),
        ),
    ]
