# Generated by Django 5.2.13 on 2026-04-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_target_language_userlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
