# Generated by Django 5.2.13 on 2026-04-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_last_activity_date_user_streak'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('endpoint', models.CharField(max_length=50)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'endpoint', 'attempted_at'], name='accounts_ra_ip_addr_ca6cf2_idx')],
            },
        ),
    ]
