# Generated by Django 5.2.13 on 2026-09-02 17:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_hosting', models.BooleanField(default=False)),
                ('promoted_to_visitor', models.BooleanField(default=False)),
                ('lookup_failed', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address'], name='pageview_an_ip_addr_a87a1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='pageview_an_user_id_72d5ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.CharField(db_index=True, help_text='Ties this view to its later duration report. Not a visitor identifier -- generated fresh per view, never reused.', max_length=32)),
                ('page', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('referrer', models.URLField(blank=True, max_length=300)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('visitor_key', models.CharField(db_index=True, max_length=16)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='pageview_analytics.visitorlocation')),
            ],
            options={
                'indexes': [models.Index(fields=['page', 'created_at'], name='pageview_an_page_a6cb2e_idx'), models.Index(fields=['visitor_key', 'created_at'], name='pageview_an_visitor_f92bf1_idx')],
            },
        ),
    ]
