# Generated by Django 5.2.13 on 2026-04-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
