# Generated by Django 5.2.13 on 2026-04-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_phrase_pronunciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='word_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
