# Generated by Django 5.2.13 on 2026-04-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_favoritephrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='conjugations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
